/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'cctv' : IDL.Null,
  'computer' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ServiceRequest = IDL.Record({
  'customerName' : IDL.Text,
  'status' : Status,
  'serviceType' : ServiceType,
  'requestId' : IDL.Nat,
  'adminReply' : IDL.Opt(IDL.Text),
  'submittedAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'repliedAt' : IDL.Opt(IDL.Int),
  'problemDescription' : IDL.Text,
  'phone' : IDL.Text,
  'hasNewReply' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Customer = IDL.Record({
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'customerName' : IDL.Text,
  'requestId' : IDL.Nat,
  'submittedAt' : IDL.Int,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'phone' : IDL.Text,
  'reviewId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, ServiceType], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getAverageRating' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getCustomerServiceRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getNewRequestsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getReviewByRequestId' : IDL.Func([IDL.Nat], [IDL.Opt(Review)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getServiceRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ServiceRequest)],
      ['query'],
    ),
  'getUnreadServiceRequestsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasUnreadServiceRequests' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markRequestAsRead' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'replyToServiceRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'submitServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateServiceRequestStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({ 'cctv' : IDL.Null, 'computer' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ServiceRequest = IDL.Record({
    'customerName' : IDL.Text,
    'status' : Status,
    'serviceType' : ServiceType,
    'requestId' : IDL.Nat,
    'adminReply' : IDL.Opt(IDL.Text),
    'submittedAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'repliedAt' : IDL.Opt(IDL.Int),
    'problemDescription' : IDL.Text,
    'phone' : IDL.Text,
    'hasNewReply' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const Customer = IDL.Record({
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'customerName' : IDL.Text,
    'requestId' : IDL.Nat,
    'submittedAt' : IDL.Int,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'phone' : IDL.Text,
    'reviewId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ServiceType],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getAverageRating' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getCustomerServiceRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getNewRequestsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getReviewByRequestId' : IDL.Func([IDL.Nat], [IDL.Opt(Review)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getServiceRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ServiceRequest)],
        ['query'],
      ),
    'getUnreadServiceRequestsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasUnreadServiceRequests' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markRequestAsRead' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'replyToServiceRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'submitServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateServiceRequestStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };