/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'serviceType' : ServiceType,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface Review {
  'customerName' : string,
  'requestId' : bigint,
  'submittedAt' : bigint,
  'comment' : string,
  'rating' : bigint,
  'phone' : string,
  'reviewId' : bigint,
}
export interface ServiceRequest {
  'customerName' : string,
  'status' : Status,
  'serviceType' : ServiceType,
  'requestId' : bigint,
  'adminReply' : [] | [string],
  'submittedAt' : bigint,
  'isRead' : boolean,
  'repliedAt' : [] | [bigint],
  'problemDescription' : string,
  'phone' : string,
  'hasNewReply' : boolean,
}
export type ServiceType = { 'cctv' : null } |
  { 'computer' : null };
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[string, string, string, ServiceType], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getAverageRating' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], [] | [Customer]>,
  'getCustomerServiceRequests' : ActorMethod<[string], Array<ServiceRequest>>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getNewRequestsCount' : ActorMethod<[], bigint>,
  'getReviewByRequestId' : ActorMethod<[bigint], [] | [Review]>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getServiceRequest' : ActorMethod<[bigint], [] | [ServiceRequest]>,
  'getUnreadServiceRequestsCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasUnreadServiceRequests' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markRequestAsRead' : ActorMethod<[bigint, string], undefined>,
  'replyToServiceRequest' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitReview' : ActorMethod<[bigint, bigint, string], bigint>,
  'submitServiceRequest' : ActorMethod<
    [string, string, ServiceType, string],
    bigint
  >,
  'updateServiceRequestStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];